### ISSUE TITLE
Which callback should be invoked If the key is not exist?

### ISSUE THREAD

**Issue by simpleton** [Naturally-Being/G-Rex#13]
I've found only the `onComplete` will be invoked, it's really odd.

**Comment by grodin** [comment]
That's exactly the right answer. If the key is not found, then the
`Observable` has to be empty, so it completes without emitting anything.

We don't want to return `null` in `onNext` since then there's no way to
distinguish between "no key found" and "value null found at key".

This is similar to `Optional` in Java 8/Guava.
On 12 May 2015 8:18 pm, "Sim Sun" <notifications@github.com> wrote:

I've found only the onComplete will be invoked, it's really odd.

—
Reply to this email directly or view it on GitHub
<https://github.com/Naturally-Being/G-Rex/issues/13>.

**Comment by simpleton** [comment]
Thanks for your quick feedback. Yep, return `null` in `onNext` is evil, but in current source code, we can't know the key is found or not. Maybe we can throw the exception which we can get it in `onError`.

**Comment by grodin** [comment]
I think we might be misunderstanding each other here: if something is found at the key (including `null`), it will be returned in `onNext`, then `onComplete` will be called immediately after. If nothing is found, then `onComplete` is called directly. Anything else is a bug!

We wouldn't want to use `onError` for an expected event since that method is supposed to be used in the same way as throwing an Exception.

If you want to check if something is found without actually getting the value, you could use the [`Observable.exists()` operator](http://reactivex.io/documentation/operators/contains.html).

**Comment by simpleton** [comment]
cool, make sense. thx :dancer:

**Comment by grodin** [comment]
No problem, happy to help!
