### ISSUE TITLE
Compared to Nhachicha/SnappyDB?

### ISSUE THREAD

**Issue by sirvon** [Naturally-Being/G-Rex#5]
can you compare your lib with snappyDB

https://github.com/nhachicha/SnappyDB

what being advantages/disadvantages that you can quickly see?

**Comment by chris-horner** [comment]
From looking quickly, Snappy DB seems to be solving a similar problem slightly differently. Its functionality is a bit more database-y, allowing you to do advanced `FROM` and `TO` operations with key sets. It also appears to try and persist objects with minimal disk footprint.

G-Rex is really only for simple "store this stuff, then gimme the stuff" operations. Because of this however, it has a much simpler API (it's not trying to be super fancy). Because G-Rex leans on RxJava, it also makes it particularly easy to deal with threading and composition with other operations.

I only looked quickly, but it seems like if you cared about threading with Snappy DB, you'd have to take care of it yourself.
